services:
  nats:
    container_name: realtime-messaging-nats
    image: nats:2.11
    ports:
      - "4222:4222"
  publisher:
    build:
      context: .
      dockerfile: docker/publisher/Dockerfile
    image: publisher-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - nats
  subscriber:
    build:
      context: .
      dockerfile: docker/subscriber/Dockerfile
    image: subscriber-service:latest
    ports:
      - "3001:3001"
    depends_on:
      - nats
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  auth-cli:
    build:
      context: .
      dockerfile: docker/auth-cli/Dockerfile
