services:
  nats:
    container_name: realtime-messaging-nats
    image: nats:2.11
    ports:
      - "4222:4222"
  publisher:
    build:
      context: .
      dockerfile: docker/publisher/Dockerfile
    image: publisher-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - nats
  subscriber:
    build:
      context: .
      dockerfile: docker/subscriber/Dockerfile
    image: subscriber-service:latest
    ports:
      - "3001:3001"
    depends_on:
      - nats
