global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "publisher_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["publisher:3000"]

  - job_name: "subscriber_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["subscriber:3001"]
