name: Go

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -cover ./...
